data:
  type: SEED
  window_size: 1
  # the subject index of the dataset
  subject_index: 3
  # the upper directory of the dataset
  prefix: /home/yansenwang/data/

network:
  type: MMM_Encoder
  depth: 6
  num_heads: 8
  encoder_dim: 64
  channel_num: 79
  in_chans: 5
  pe_type: 2d

decoder_network: # used only during pre-training. Can be omitted if only finetuning.
  type: MMM_Encoder
  depth: 6
  encoder_dim: 64
  channel_num: 79
  in_chans: 16

model:
  type: MMM_Finetune
  task: multiclassification
  # set up pre-trained model path, leave blank for training from scratch
  # E.g.
  model_path: /path/to/tuh_pretrained_encoder_base.pt
  optimizer: Adam
  lr: 0.00005
  weight_decay: 0.005
  loss_fn: cross_entropy
  metrics: [accuracy]
  observe: accuracy
  lower_is_better: False
  max_epochs: 100
  early_stop: 70
  batch_size: 32
  out_size: 3
  mask_ratio: 0.

runtime:
  seed: 51
  use_cuda: true
  output_dir: outputs/MMM_SEED/3/